# Travis CI script

language: c

os:
- linux
- osx

dist: trusty

env:
- BUILD_TYPE=default CURVE=tweetnacl
- BUILD_TYPE=android CURVE=tweetnacl
- BUILD_TYPE=cmake CURVE=tweetnacl
- BUILD_TYPE=default CURVE=libsodium
- BUILD_TYPE=default
- BUILD_TYPE=coverage CURVE=tweetnacl
- BUILD_TYPE=valgrind CURVE=tweetnacl

matrix:
  exclude:
    -  env: BUILD_TYPE=coverage CURVE=tweetnacl
       os: osx
    -  env: BUILD_TYPE=valgrind CURVE=tweetnacl
       os: osx
  include:
    -  env: BUILD_TYPE=default CURVE=tweetnacl IPv6=ON
       os: linux
       dist: precise
       sudo: false

sudo: required

addons:
  apt:
    packages:
    - cmake
    - lcov
    - valgrind

before_install:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update; brew install binutils ; fi

before_script:
# ZMQ stress tests need more open socket (files) than the usual default
# On OSX, it seems the way to set the max files limit is constantly changing, so
# try to use all known knobs to ensure compatibility across various versions
- if [ $TRAVIS_OS_NAME == "osx" ] ; then sudo sysctl -w kern.maxfiles=64000 ; sudo sysctl -w kern.maxfilesperproc=64000 ; sudo launchctl limit maxfiles 64000 64000 ; ulimit -n 64000; fi

# Build and check this project according to the BUILD_TYPE
script: ./ci_build.sh
